### ISSUE TITLE
Error using pyxero with google app engine

### ISSUE THREAD

**Issue by neerajgodbole** [freakboy3742/pyxero#146]
I have followed the steps to generate a consumer key and the rsa key, but whenever I try to test my application, it doesnt work, giving me the following sequence of errors:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Program Files (x86)\Google\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "C:\Users\neera\OneDrive\GoPomelo\go-accounting\InvoicesHandler.py", line 51, in get
    xero = Xero(credentials)
  File "C:\Users\neera\OneDrive\GoPomelo\go-accounting\xero\api.py", line 47, in __init__
    user_agent))
  File "C:\Users\neera\OneDrive\GoPomelo\go-accounting\xero\manager.py", line 21, in __init__
    self.user_agent = 'pyxero/%s ' % VERSION + requests.utils.default_user_agent()
  File "C:\Users\neera\OneDrive\GoPomelo\go-accounting\requests\utils.py", line 537, in default_user_agent
    p_system = platform.system()
  File "C:\Python27\lib\platform.py", line 1263, in system
    return uname()[0]
  File "C:\Python27\lib\platform.py", line 1159, in uname
    release,version,csd,ptype = win32_ver()
  File "C:\Python27\lib\platform.py", line 632, in win32_ver
    from _winreg import OpenKeyEx, QueryValueEx, CloseKey, HKEY_LOCAL_MACHINE
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\python\sandbox.py", line 963, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named _winreg
```

I have written code for an invoice handler using webapp2 and this is my code:

```
class InvoicesHandler(webapp2.RequestHandler):
    def get(self):
        template_values = {
        	"header":"Invoices",
        	"body":"Connecting to Xero API"
        }
        template = JINJA_ENV.get_template('invoices.html')
        self.response.write(template.render(template_values))

        os.environ['SERVER_SOFTWARE'] = 'Dev'

        with open("privatekey.pem") as keyfile:
        	RSA_KEY = keyfile.read()

        credentials = PrivateCredentials(consumerKey, RSA_KEY)
        xero = Xero(credentials)
        xero.contacts.all()
```

Any responses will be appreciated as I really don't know what could be causing the issue here.
Thanks!

**Comment by aidanlister** [comment]
Google app engine isn't real python, so it's not supported in this library. See other issues with similar problems:
https://github.com/freakboy3742/pyxero/issues/57

**Comment by onejgordon** [comment]
I was having similar issues but was eventually able to get things working via inspiration from https://github.com/hamish/gae_xero, an old version of requests (2.3.0), and a minor patch to oauthlib to use the rsaalgorithm from pycrypto instead of cryptography. Happy to share a diff with anyone if useful.

**Comment by onejgordon** [comment]
A few people requested the diff that worked for me: this is all it took.

```
./oauthlib/oauth1/rfc5849/signature.py

> import Crypto
473,474c474,479
<         import jwt.algorithms as jwtalgo
<         _jwtrs1 = jwtalgo.RSAAlgorithm(jwtalgo.hashes.SHA1)
---
>         # import jwt.algorithms as jwtalgo
>         # _jwtrs1 = jwtalgo.RSAAlgorithm(jwtalgo.hashes.SHA1)
>         # Edits to use pycrypto instead of cryptography to get working on GAE
>         from jwt.contrib.algorithms.pycrypto import RSAAlgorithm
>         from Crypto.Hash import SHA
>         _jwtrs1 = RSAAlgorithm(SHA)
```
