### ISSUE TITLE
import xero.auth ImportError: No module named auth

### ISSUE THREAD

**Issue by mohammad-ghanbari** [freakboy3742/pyxero#195]
pyxero was working for me, but now it is giving this error:

Unhandled exception in thread started by <function wrapper at 0x7fc170a2e230>
Traceback (most recent call last):
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mohamad/Projects/ERP/server/ERP/urls.py", line 20, in <module>
    from accounting.views import PaymentTermViewSet, XeroView
  File "/home/mohamad/Projects/ERP/server/apps/accounting/views.py", line 17, in <module>
    import xero.auth
ImportError: No module named auth
Performing system checks...

I tried to uninstall and install the pyxero, but it doesn't solve the probelm.

The following is my other packages installed:

asn1crypto==0.22.0
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
coreapi==2.1.1
cryptography==2.0
dj-database-url==0.3.0
dj-static==0.0.6
Django==1.9
django-allauth==0.29.0
django-appconf==0.6
django-compressor==1.6
django-cors-headers==2.1.0
django-extensions==1.7.7
django-filter==1.0.1
django-rest-auth==0.8.2
django-rest-swagger==2.0.7
djangorestframework==3.5.1
drf-nested-routers==0.9.0
enum34==1.1.6
gunicorn==19.1.1
idna==2.5
ipaddress==1.0.18
itypes==1.1.0
oauthlib==2.0.2
olefile==0.44
openapi-codec==1.2.0
Pillow==4.0.0
psycopg2==2.4.5
pycparser==2.18
PyJWT==1.4.0
python-dateutil==2.6.1
python-openid==2.2.5
pyxero==0.9.0
requests==2.18.1
requests-oauthlib==0.8.0
simplejson==3.10.0
six==1.10.0
static3==0.5.1
uritemplate==3.0.0
urllib3==1.21.1
whitenoise==3.2.3

**Comment by romgar** [comment]
Hi @mohammad-ghanbari ! Was it working with version `0.8.0`?

**Comment by mohammad-ghanbari** [comment]
I don't know what was the original version (it was last week that it was working)
Now I installed version 0.8.0, still getting same error

**Comment by mohammad-ghanbari** [comment]
I found the problem. In my app I had added another file called xero.py and that was causing a name conflict with the sdk itself.
