### ISSUE TITLE
ValueError: "'module' object has no attribute 'RSAAlgorithm'" while evaluating

### ISSUE THREAD

**Issue by miebakso** [freakboy3742/pyxero#220]
I encounter this error while trying integrating xero to odoo, i have pip install cryptography but still have this error, i am using Python 2.7

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 546, in _handle_exception
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 583, in dispatch
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 319, in _call_function
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 316, in checked_call
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 812, in __call__
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 412, in response_wrap
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\web\controllers\main.py", line 955, in exec_workflow
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 1120, in exec_workflow
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 888, in proxy_method
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\http.py", line 115, in dispatch_rpc
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 37, in dispatch
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 188, in exec_workflow
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 182, in exec_workflow_cr
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\service\model.py", line 164, in execute_cr
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\models.py", line 3572, in signal_workflow
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\__init__.py", line 85, in trg_validate
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\service.py", line 91, in validate
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\instance.py", line 80, in validate
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 120, in process
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 248, in _split_test
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 257, in _join_test
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 95, in create
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 116, in process
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 162, in _execute
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 313, in wkf_expr_execute
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\workflow\workitem.py", line 291, in wkf_expr_eval_expr
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\tools\safe_eval.py", line 314, in safe_eval
  File "", line 1, in <module>
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\api.py", line 266, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\franchisee\models\franchisee.py", line 61, in invoice_validate
  File "C:\Program Files (x86)\Odoo8\server\.\openerp\api.py", line 266, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\ciptadlab\models\franchisee.py", line 15, in create
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\ciptadlab\models\franchisee.py", line 43, in generate_xero_invoice
  File "C:\Program Files (x86)\Odoo8\server\.\xero\basemanager.py", line 189, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\.\requests\api.py", line 112, in post
  File "C:\Program Files (x86)\Odoo8\server\.\requests\api.py", line 58, in request
  File "C:\Program Files (x86)\Odoo8\server\.\requests\sessions.py", line 494, in request
  File "C:\Program Files (x86)\Odoo8\server\.\requests\sessions.py", line 437, in prepare_request
  File "C:\Program Files (x86)\Odoo8\server\.\requests\models.py", line 309, in prepare
  File "C:\Program Files (x86)\Odoo8\server\.\requests\models.py", line 540, in prepare_auth
  File "C:\Program Files (x86)\Odoo8\server\.\requests_oauthlib\oauth1_auth.py", line 80, in __call__
  File "C:\Program Files (x86)\Odoo8\server\.\oauthlib\oauth1\rfc5849\__init__.py", line 314, in sign
  File "C:\Program Files (x86)\Odoo8\server\.\oauthlib\oauth1\rfc5849\__init__.py", line 151, in get_oauth_signature
  File "C:\Program Files (x86)\Odoo8\server\.\oauthlib\oauth1\rfc5849\signature.py", line 510, in sign_rsa_sha1_with_client
  File "C:\Program Files (x86)\Odoo8\server\.\oauthlib\oauth1\rfc5849\signature.py", line 501, in sign_rsa_sha1
  File "C:\Program Files (x86)\Odoo8\server\.\oauthlib\oauth1\rfc5849\signature.py", line 479, in _jwt_rs1_signing_algorithm
ValueError: "'module' object has no attribute 'RSAAlgorithm'" while evaluating
u'invoice_validate()

`
def generate_xero_invoice(self, data):
		
		with open("C:\\OpenSSL\\bin\\publickey.cer") as keyfile:
			rsa_key = keyfile.read()
	
		credentials = PrivateCredentials('XHTKCYJGSUC1TM8AXQBRCKAGPKDZ5W', rsa_key)
		xero = Xero(credentials)
		print("test123123123ajsdhkajsjhdjkahjsdhkjsdhfjshajkdhfjasdkh")
		invoice = {
			"Type": "ACCREC", 	
			"Contact": {
				"Name": "Test"
			},
			"SubTotal": 87.11,
			"Total": 87.11,
			"LineItems": {
				"LineItem": {
					"Description": "coba",
					"Quantity": "test",
					"UnitAmount": 10
				}
			}
		}
		#ERROR WHEN CALLING METHOD SAVE(), ValueError: "'module' object has no attribute 'RSAAlgorithm'" while evaluating
		xero.invoices.save(invoice)`

**Comment by freakboy3742** [comment]
Closing since the feature no longer exists.
