### ISSUE TITLE
Authorisation Issue using Python 3

### ISSUE THREAD

**Issue by norahw** [freakboy3742/pyxero#235]
Hi there

I have copied the example public oauth files and changed the SocketServer library to socketserver as I am using Python 3.6.

I get the following error:
Serving path: /verified
127.0.0.1 - - [12/Jul/2018 07:47:22] "GET /verified HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51631)
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/anaconda/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/anaconda/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/anaconda/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/anaconda/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/anaconda/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "runserver.py", line 123, in do_GET
    self.page_response(title='Xero Contacts', body=page_body)
  File "runserver.py", line 40, in page_response
    self.copyfile(f, self.wfile)
  File "/anaconda/lib/python3.6/http/server.py", line 800, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/anaconda/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/anaconda/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'

**Comment by Wozzyy** [comment]
Hi @norahw sorry you didn't get a reply, but this example has been removed from the project as OAuth 1.0 apps were disabled by Xero some years ago. Everything now must be OAuth 2.0. There are some examples in the PyXero README.

**Comment by freakboy3742** [comment]
Closing as the feature no longer exists.
