### ISSUE TITLE
Could not deserialize key data. Error with Certificate.

### ISSUE THREAD

**Issue by emalves** [freakboy3742/pyxero#237]
I'm creating a Private App, but I'm having trouble accessing it through pyxero.

This is my code:
```
from xero import Xero
from cryptography.x509 import load_pem_x509_certificate
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.hazmat.backends import default_backend
from xero.auth import PrivateCredentials

CONSUMER_KEY = "CONSUMER_KEY"
CERTIFICATE_PATH = "keys/xero.cer"

with open(CERTIFICATE_PATH) as keyfile:
    rsa_key = keyfile.read()
credentials = PrivateCredentials(CONSUMER_KEY, rsa_key)
xero = Xero(credentials)
print(xero.contacts.all())
```

This is the content of the xero.cer:

```
-----BEGIN CERTIFICATE-----
MIIC8DCCAlmgAwIBAgIJANik4udv2fZWMA0GCSqGSIb3DQEBCwUAMIGQMQswCQYD
VQQGEwJQVDEQMA4GA1UECAwHU2V0dWJhbDEQMA4GA1UEBwwHU2V0dWJhbDERMA8G
A1UECgwIRnVlbGdyYW0xEjAQBgNVBAsMCU1hcmtldGluZzERMA8GA1UEAwwIRnVl
bGdyYW0xIzAhBgkqhkiG9w0BCQEWFHN1cHBvcnRAZnVlbGdyYW0uY29tMB4XDTE4
MDczMDExNDE0N1oXDTIzMDcyOTExNDE0N1owgZAxCzAJBgNVBAYTAlBUMRAwDgYD
VQQIDAdTZXR1YmFsMRAwDgYDVQQHDAdTZXR1YmFsMREwDwYDVQQKDAhGdWVsZ3Jh
bTESMBAGA1UECwwJTWFya2V0aW5nMREwDwYDVQQDDAhGdWVsZ3JhbTEjMCEGCSqG
SIb3DQEJARYUc3VwcG9ydEBmdWVsZ3JhbS5jb20wgZ8wDQYJKoZIhvcNAQEBBQAD
gY0AMIGJAoGBAMtulWbbehT15baLPmNf+ILbnHhDjAP1c0ynWC0kao2iqnPGQr32
pH2USnFbMco/IXd6cTbevkH4Y1EQy+N3lDpnrIGmqQ0LvMOsrERgTAVNmD/ViMxP
C1hwqN/fICqenXyFG5P7KSbaZ6GgYsIZ3sKA30aniGfaXB2R9p3gKJetAgMBAAGj
UDBOMB0GA1UdDgQWBBQ3kLM0tAvIWWEY0RkQDCsmJrUNbDAfBgNVHSMEGDAWgBQ3
kLM0tAvIWWEY0RkQDCsmJrUNbDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4GBAABQN31lgHedJuUdhbA0ew7L3jGqT5m9G8kVoy1CZbr/mJnP29AuznEvnVku
66IMlKCnA/79vVMEPx29y/SBenVkgASTXeFkdR7a4LujChv0ohXp955DVREKXNoD
WIkCei0P+urU4YpnnIJl8kJUm0u8GoRDSwRyfL3W7v5QOi5Q
-----END CERTIFICATE-----
```

This is the traceback log:
```
Traceback (most recent call last):
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\jwt\algorithms.py", line 167, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\primitives\serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1015, in load_pem_private_key
    password,
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1234, in _load_key
    self._handle_key_loading_error()
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1292, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xero_handler.py", line 14, in <module>
    print(xero.contacts.all())
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\xero\basemanager.py", line 189, in wrapper
    params=params, timeout=timeout)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 540, in prepare_auth
    r = auth(self)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\requests_oauthlib\oauth1_auth.py", line 88, in __call__
    unicode(r.url), unicode(r.method), None, r.headers)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth1\rfc5849\__init__.py", line 314, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth1\rfc5849\__init__.py", line 151, in get_oauth_signature
    sig = self.SIGNATURE_METHODS[self.signature_method](base_string, self)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 510, in sign_rsa_sha1_with_client
    return sign_rsa_sha1(base_string, client.rsa_key)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 502, in sign_rsa_sha1
    key = _prepare_key_plus(alg, rsa_private_key)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 583, in _prepare_key_plus
    return alg.prepare_key(keystr)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\jwt\algorithms.py", line 169, in prepare_key
    key = load_pem_public_key(key, backend=default_backend())
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\primitives\serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1041, in load_pem_public_key
    self._handle_key_loading_error()
  File "C:\Users\emalv\AppData\Local\Programs\Python\Python36\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1292, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
```

**Comment by emalves** [comment]
I've fixed it, the problem was I was passing the public key and not private key into the PrivateCredentials constructor.
