### ISSUE TITLE
Authorisation issue

### ISSUE THREAD

**Issue by Megha-Navsoft** [freakboy3742/pyxero#290]
Hi,
I'm trying to execute the public_oauth_flow example. I have added the consumer_key and consumer_secret of my app. When I'm clicking on the "Connect to Xero" button, I'm getting the following error. Can you please guide me on why I'm getting this error?

```
Exception happened during processing of request from ('127.0.0.1', 46174)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "runserver.py", line 73, in do_GET
    consumer_key, consumer_secret, callback_uri='http://localhost:8000/oauth')
  File "/home/megha/Documents/xero-test-app/venv/lib/python3.6/site-packages/xero/auth.py", line 159, in __init__
    self._init_credentials(oauth_token, oauth_token_secret)
  File "/home/megha/Documents/xero-test-app/venv/lib/python3.6/site-packages/xero/auth.py", line 190, in _init_credentials
    self._process_oauth_response(response)
  File "/home/megha/Documents/xero-test-app/venv/lib/python3.6/site-packages/xero/auth.py", line 237, in _process_oauth_response
    self._handle_error_response(response)
  File "/home/megha/Documents/xero-test-app/venv/lib/python3.6/site-packages/xero/auth.py", line 244, in _handle_error_response
    raise XeroUnauthorized(response)
xero.exceptions.XeroUnauthorized: Unknown Consumer (Realm: , Key: 2EA23154B5504C9C861400AE9C1426BC)
```

**Comment by freakboy3742** [comment]
From the look of it, the credentials you've provided aren't valid. Without any other details, my guess would be confusion over whether your credentials are oAuth1 or oAuth2.

**Comment by Megha-Navsoft** [comment]
> From the look of it, the credentials you've provided aren't valid. Without any other details, my guess would be confusion over whether your credentials are oAuth1 or oAuth2.

I have created an app on their website and took the credentials from it. I didn't get an option to choose OAuth version. I assumed it would be OAuth2. How do I check the version?
