### ISSUE TITLE
Invoice: LineItem with blanks fields causes errors

### ISSUE THREAD

**Issue by mattbriancon** [freakboy3742/pyxero#52]
I'm using `HEAD` and a test account to get my Xero integration working but I ran into a problem when I created a blank invoice.  Even though I never added it explicitly, the invoice had a single line item with all blank fields.  Trying to request that invoice caused an error:

```python
>>> inv = xero.invoices.get('<invoice id>')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 220, in wrapper
    data = self.convert_to_dict(self.walk_dom(dom))
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 119, in convert_to_dict
    data = self.convert_to_dict(deep_list[1])
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 110, in convert_to_dict
    data = self.convert_to_dict(data)
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 119, in convert_to_dict
    data = self.convert_to_dict(deep_list[1])
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 110, in convert_to_dict
    data = self.convert_to_dict(data)
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 119, in convert_to_dict
    data = self.convert_to_dict(deep_list[1])
  File "/home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py", line 128, in convert_to_dict
    out = deep_list[0]
IndexError: tuple index out of range
>>> import pdb
>>> pdb.pm()
> /home/vagrant/.virtualenvs/app/src/pyxero-master/xero/manager.py(128)convert_to_dict()
-> out = deep_list[0]
(Pdb) deep_list
()
```

The XML as returned by the API Previewer:

```xml
<LineItems>
    <LineItem />
</LineItems>
```

It seems `Manager.convert_to_dict` is mishandling the self-closing tag.

**Comment by aidanlister** [comment]
This is fixed now!

```
(Pdb) inv = xeroconn.invoices.get('ed3ba32b-679a-4031-a4ac-b0e0db2a5e5a')
(Pdb) pprint.pprint(inv)
[{'AmountDue': 0.0,
  'AmountPaid': 0.0,
  'Attachments': [],
  'BrandingThemeID': 'aefae6d5-7bbe-4e2e-aadc-302cd07a0fc1',
  'Contact': {'Addresses': [{'AddressType': 'POBOX',
                             'AttentionTo': '',
                             'City': '',
                             'Country': '',
                             'PostalCode': '',
                             'Region': ''},
                            {'AddressType': 'STREET',
                             'AttentionTo': '',
                             'City': '',
                             'Country': '',
                             'PostalCode': '',
                             'Region': ''}],
              'BankAccountDetails': '',
              'ContactGroups': [],
              'ContactID': '42771b60-19a7-4692-af81-dd9f9b9362d4',
              'ContactPersons': [],
              'ContactStatus': 'ACTIVE',
              'DefaultCurrency': 'AUD',
              'EmailAddress': 'info@abfl.com',
              'FirstName': 'Trish',
              'HasValidationErrors': False,
              'IsCustomer': True,
              'IsSupplier': True,
              'LastName': 'Rawlings',
              'Name': 'ABC Furniture',
              'Phones': [{'PhoneAreaCode': '',
                          'PhoneCountryCode': '',
                          'PhoneNumber': '',
                          'PhoneType': 'MOBILE'},
                         {'PhoneAreaCode': '',
                          'PhoneCountryCode': '',
                          'PhoneNumber': '',
                          'PhoneType': 'DDI'},
                         {'PhoneAreaCode': '0800',
                          'PhoneCountryCode': '',
                          'PhoneNumber': '124578',
                          'PhoneType': 'DEFAULT'},
                         {'PhoneAreaCode': '',
                          'PhoneCountryCode': '',
                          'PhoneNumber': '',
                          'PhoneType': 'FAX'}],
              'PurchasesTrackingCategories': [],
              'SalesTrackingCategories': [],
              'UpdatedDateUTC': datetime.datetime(2015, 5, 10, 5, 45, 44, 690000)},
  'CreditNotes': [],
  'CurrencyCode': 'AUD',
  'CurrencyRate': 1.0,
  'Date': datetime.datetime(2015, 6, 6, 0, 0),
  'DateString': '2015-06-06T00:00:00',
  'DueDate': datetime.datetime(2015, 6, 6, 0, 0),
  'DueDateString': '2015-06-06T00:00:00',
  'HasAttachments': False,
  'HasErrors': False,
  'InvoiceID': 'ed3ba32b-679a-4031-a4ac-b0e0db2a5e5a',
  'InvoiceNumber': 'ORC1088',
  'IsDiscounted': False,
  'LineAmountTypes': 'Exclusive',
  'LineItems': [{'Tracking': [], 'ValidationErrors': []}],
  'Overpayments': [],
  'Payments': [],
  'Prepayments': [],
  'Reference': '',
  'SentToContact': False,
  'Status': 'DRAFT',
  'SubTotal': 0.0,
  'Total': 0.0,
  'TotalTax': 0.0,
  'Type': 'ACCREC',
  'UpdatedDateUTC': datetime.datetime(2015, 6, 6, 8, 4, 56, 660000)}]
```
